stages:
  - build
  - test
  - package
  - deploy
  
build: # JOB이름
  image: eclipse-temurin:17
  stage: build
  script:
    - ./gradlew clean build
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 10 min

test:
  image: eclipse-temurin:17
  stage: test
  script: ./gradlew test

package:
  image: hanseu9839/photocard-server
  stage: package
  variables:
    IMAGE_NAME: hanseu9839/photocard-server
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_HUB_USER --password-stdin < $DOCKER_HUB_PW
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  after_script:
    - docker logout

deploy:
  stage: deploy
  tags:
    - photocard-build-server
  before_script:
    - docker login -u $DOCKER_HUB_USER --password-stdin < $DOCKER_HUB_PW
  script:
    - docker stop photocardback-back || true
    - docker rm photocardback-back || true
    - docker rmi hanseu9839/photocard-server || true
    - docker run -d --restart always -p 8080:8080/tcp --name photocard-server hanseu9839/photocard-server
  after_script:
    - docker logout
  when: on_success
  only:
    - main
