photo-card-job: # JOB 이름
  stage: deploy # build, test, deploy 3단계 스테이지 중 하나
  only:
    - main # main 브랜치 이벤트 발생시 실행
  script:
    - echo "Hello world" # 실행할 스크립트
  tags:
    - photocardBack # photocardBack 태그가 달린 runner에서 실행