server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: "dev"
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://photocard.site/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
          naver:
            client_id: ${NAVER_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://photocard.site/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openai.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL} # 추후 암호화 예정
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD} # 추후 encrypt를 사용하여 암호화할 예정
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: hans9839@naver.com
    password: YTSUYG7MQBBY
    properties:
      mail:
        smtp:
          starttls:
            enabel: true
            required: true
          auth:
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
          ssl:
            #trust: smtp.naver.com
            enable: true
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql:
                BasicBinder: trace
        springframework:
          security: DEBUG

jsypt:
  encryptor:
    bean: jasyptStringEncryptor
jwt:
  secret: n42VY/OqNLyuiwq5wr+f+Ko5ozRqwlRHCOyufbkhvgo=

cloud:
  aws:
    s3:
      bucket: photocardsite
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

file:
  path: C:\\dev\\file\\image

firebase:
  credentials-path: C:\dev\keys\photocard_firebase
  storage-name: photocard-f2e87.appspot.com