server:
  port: 8080
jasypt:
  encryptor:
    bean: jasyptEncryptorAES
spring:
  profiles:
    active: dev # default
    group:
      local: "local, datasource, jpa, mail, logging, jasypt"
      dev: "dev, datasource, jpa, mail, logging, jasypt"