server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: local # default
    group:
      local: "local, datasource, jpa, mail, logging, jasypt"
      dev: "dev, datasource, jpa, mail, logging, jasypt"