server:
  port: 8080
  servlet:
    context-path: /api
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev # default
    group:
      local: "local, datasource, jpa, mail, logging, jasypt"
      dev: "dev, datasource, jpa, mail, logging, jasypt"

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics, info