server:
  port: 8080

spring:
  profiles:
    default: dev # 기본 환경 설정을 dev로 설정한다.

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.154.62.23:3306/real_world?serverTimezone=UTC&characterEncoding=UTF-8 # 추후 암호화 예정
    username: real_world
    password: 1234 # 추후 encrypt를 사용하여 암호화할 예정
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: hans9839@naver.com
    password: YTSUYG7MQBBY
    properties:
      mail:
        smtp:
          starttls:
            enabel: true
            required: true
          auth:
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
          ssl:
            #trust: smtp.naver.com
            enable: true
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql:
                BasicBinder: trace
        springframework:
          security: TRACE

jsypt:
  encryptor:
    bean: jasyptStringEncryptor
jwt:
  secret: n42VY/OqNLyuiwq5wr+f+Ko5ozRqwlRHCOyufbkhvgo=
